CREATE TABLE DIM_INDICATOR (

DIM_INDICATOR_ID                   NUMBER(15,0)  NOT NULL,
DIM_INDICATOR_CODE                 VARCHAR2(50), 
DIM_INDICATOR_TOPIC                VARCHAR2(400), 
DIM_INDICATOR_NAME                 VARCHAR2(400), 
DIM_INDICATOR_SHORT_DEFINITION         VARCHAR2(1000), 
DIM_INDICATOR_LONG_DEFINITION          VARCHAR2(4000), 
DIM_INDICATOR_MEASURE_UNIT             VARCHAR2(20), 
DIM_INDICATOR_PERIODICITY              VARCHAR2(40), 
DIM_INDICATOR_BASE_PERIOD              VARCHAR2(50), 
DIM_INDICATOR_OTHER_NOTES            VARCHAR2(2000), 
DIM_INDICATOR_AGGREGATION_METHOD       VARCHAR2(50), 
DIM_INDICATOR_LIMITATION_EXCEPTION    VARCHAR2(4000), 
DIM_INDICATOR_NOTES_ORIGIN_SOURCE      VARCHAR2(4000), 
META_INSERTION_DATE    DATE, 
META_UPDATE_DATE    DATE, 
META_DATA_SOURCE       VARCHAR2(20),

CONSTRAINT PK_DIM_INDICATOR PRIMARY KEY (DIM_INDICATOR_ID)
using index TABLESPACE DIM_INDEX
) 
TABLESPACE DIM_DATA;


CREATE SEQUENCE SEQ_DIM_INDICATOR
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

COMMENT ON TABLE  DIM_INDICATOR                                IS  'TEMPORARY TABLE OF SERIES';
COMMENT ON COLUMN DIM_INDICATOR.DIM_INDICATOR_ID               IS  'TECHNICAL UNIQUE IDENTIFIER OF SERIES';
COMMENT ON COLUMN DIM_INDICATOR.DIM_INDICATOR_CODE             IS  'FUNCTIONAL UNIQUE IDENTIFIER OF SERIES';
COMMENT ON COLUMN DIM_INDICATOR.DIM_INDICATOR_NAME             IS  'NAME OF SERIES';
COMMENT ON COLUMN DIM_INDICATOR.DIM_INDICATOR_TOPIC            IS  'TOPIC OF  SERIES';
COMMENT ON COLUMN DIM_INDICATOR.DIM_INDICATOR_SHORT_DEFINITION     IS  'SHORT DEFINITION OF SERIES';
COMMENT ON COLUMN DIM_INDICATOR.DIM_INDICATOR_LONG_DEFINITION      IS  'LONG DEFINITION OF SERIES';
COMMENT ON COLUMN DIM_INDICATOR.DIM_INDICATOR_MEASURE_UNIT         IS  'MEASURE UNIT';
COMMENT ON COLUMN DIM_INDICATOR.DIM_INDICATOR_PERIODICITY          IS  'PERIODICITY';
COMMENT ON COLUMN DIM_INDICATOR.DIM_INDICATOR_AGGREGATION_METHOD   IS  'AGGREGATION METHOD';
COMMENT ON COLUMN DIM_INDICATOR.DIM_INDICATOR_LIMITATION_EXCEPTION  IS  'LIMITATIONS AND EXCEPTION';
COMMENT ON COLUMN DIM_INDICATOR.DIM_INDICATOR_NOTES_ORIGIN_SOURCE   IS  'NOTES ORIGIN SOURCE';



CREATE OR REPLACE TRIGGER DIM_INDICATOR_ON_INSERT
BEFORE INSERT ON DIM_INDICATOR
FOR EACH ROW

BEGIN
SELECT SEQ_DIM_INDICATOR.NEXTVAL
INTO :NEW.DIM_INDICATOR_ID
FROM DUAL;
END;
/
