CREATE TABLE DIM_COUNTRY (

COUNTRY_ID             NUMBER (15,0)  NOT NULL,
COUNTRY_CODE           VARCHAR2 (20)  NOT NULL, 
COUNTRY_SHORT_NAME     VARCHAR2 (100) NOT NULL, 
COUNTRY_LONG_NAME      VARCHAR2(500)  NOT NULL, 
COUNTRY_CURRENCY_UNIT  VARCHAR2(200), 
COUNTRY_SPECIAL_NOTES  VARCHAR2(2000), 
COUNTRY_REGION         VARCHAR2(100), 
META_INSERTION_DATE    DATE, 
META_DATA_SOURCE       VARCHAR2(20),

CONSTRAINT PK_DIM_COUNTRY PRIMARY KEY (COUNTRY_ID)
using index TABLESPACE DIM_INDEX
) 
TABLESPACE DIM_DATA;


CREATE SEQUENCE SEQ_COUNTRY
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

--INITIALIATION
INSERT INTO DIM_COUNTRY (COUNTRY_ID,
COUNTRY_CODE,
COUNTRY_SHORT_NAME,
COUNTRY_LONG_NAME,
COUNTRY_CURRENCY_UNIT,
COUNTRY_SPECIAL_NOTES,
COUNTRY_REGION,
META_INSERTION_DATE,
META_DATA_SOURCE)
VALUES (-1,'#NA','#NA','#NA','#NA','#NA','#NA','01-01-1990','INIT');

COMMENT ON TABLE  DIM_COUNTRY                          IS  'TABLE OF COUNTRY';
COMMENT ON COLUMN DIM_COUNTRY.COUNTRY_ID               IS  'TECHNICAL UNIQUE IDENTIFIER OF COUNTRY';
COMMENT ON COLUMN DIM_COUNTRY.COUNTRY_CODE             IS  'FUNCTIONAL UNIQUE IDENTIFIER OF COUNTRY';
COMMENT ON COLUMN DIM_COUNTRY.COUNTRY_SHORT_NAME       IS  'SHORT NAME OF COUNTRY';
COMMENT ON COLUMN DIM_COUNTRY.COUNTRY_LONG_NAME        IS  'LONG NAME OF  COUNTRY';
COMMENT ON COLUMN DIM_COUNTRY.COUNTRY_CURRENCY_UNIT    IS  'COUNTRY_CURRENCY_UNIT';
COMMENT ON COLUMN DIM_COUNTRY.COUNTRY_SPECIAL_NOTES    IS  'SPECIAL NOTES';
COMMENT ON COLUMN DIM_COUNTRY.COUNTRY_REGION           IS  'COUNTRY REGION';
COMMENT ON COLUMN DIM_COUNTRY.META_INSERTION_DATE      IS  'META_INSERTION_DATE';
COMMENT ON COLUMN DIM_COUNTRY.META_DATA_SOURCE         IS  'META_DATA_SOURCE';

CREATE OR REPLACE TRIGGER DIM_COUNTRY_ON_INSERT
BEFORE INSERT ON DIM_COUNTRY
FOR EACH ROW

BEGIN
SELECT SEQ_COUNTRY.NEXTVAL
INTO :NEW.COUNTRY_ID
FROM DUAL;
END;
/
