INSERT INTO DIM_COUNTRY (COUNTRY_CODE,
COUNTRY_SHORT_NAME,
COUNTRY_LONG_NAME,
COUNTRY_CURRENCY_UNIT,
COUNTRY_SPECIAL_NOTES,
COUNTRY_REGION,
META_INSERTION_DATE,
META_DATA_SOURCE)
VALUES ('INX','Indonesia','Indonesia','#NA','#NA','#NA','29-10-2022','MANUAL');

INSERT INTO DIM_COUNTRY (COUNTRY_CODE,
COUNTRY_SHORT_NAME,
COUNTRY_LONG_NAME,
COUNTRY_CURRENCY_UNIT,
COUNTRY_SPECIAL_NOTES,
COUNTRY_REGION,
META_INSERTION_DATE,
META_DATA_SOURCE)
VALUES ('TWN','Taiwan','Taiwan','#NA','#NA','#NA','29-10-2022','MANUAL');

INSERT INTO DIM_COUNTRY (COUNTRY_CODE,
COUNTRY_SHORT_NAME,
COUNTRY_LONG_NAME,
COUNTRY_CURRENCY_UNIT,
COUNTRY_SPECIAL_NOTES,
COUNTRY_REGION,
META_INSERTION_DATE,
META_DATA_SOURCE)
VALUES ('KSV','Kosovo','Kosovo','#NA','#NA','#NA','29-10-2022','MANUAL');

INSERT INTO DIM_INDICATOR 
(
DIM_INDICATOR_CODE,
DIM_INDICATOR_TOPIC,
DIM_INDICATOR_NAME,
DIM_INDICATOR_SHORT_DEFINITION,
DIM_INDICATOR_LONG_DEFINITION,
DIM_INDICATOR_MEASURE_UNIT,
DIM_INDICATOR_PERIODICITY,
DIM_INDICATOR_BASE_PERIOD,
DIM_INDICATOR_OTHER_NOTES,
DIM_INDICATOR_AGGREGATION_METHOD,
DIM_INDICATOR_LIMITATION_EXCEPTION,
DIM_INDICATOR_NOTES_ORIGIN_SOURCE,
META_INSERTION_DATE,
META_UPDATE_DATE,
META_DATA_SOURCE)
VALUES ('CPI.INDEX','Corruption Perception Index','Corruption Perception Index','Corruption Perception Index','#NA','#NA','#NA','#NA','#NA','#NA','#NA','#NA','01-01-1990','01-01-1990','CPI');


COMMIT;

