---TABLESPACE CREATION---

CREATE bigfile tablespace DIM_INDEX
datafile 'C:\ORACLE\ORADATA\ORCL\DIM_INDEX_01.DBF'
SIZE 200M REUSE 
AUTOEXTEND ON MAXSIZE 4G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;


CREATE bigfile tablespace DIM_DATA
datafile 'C:\ORACLE\ORADATA\ORCL\DIM_DATA_01.DBF'
SIZE 200M REUSE 
AUTOEXTEND ON MAXSIZE 4G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;


CREATE bigfile tablespace FAC_INDEX
dataile 'C:\ORACLE\ORADATA\ORCL\FAC_INDEX_01.DBF'
SIZE 200M REUSE 
AUTOEXTEND ON MAXSIZE 4G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;


CREATE bigfile tablespace FAC_DATA
datafile 'C:\ORACLE\ORADATA\ORCL\FAC_DATA_01.DBF'
SIZE 200M REUSE 
AUTOEXTEND ON MAXSIZE 4G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;