CREATE TABLE TMP_INDICATOR (

TMP_INDICATOR_ID                   NUMBER(15,0)  NOT NULL,
TMP_INDICATOR_CODE                 VARCHAR2(50), 
TMP_INDICATOR_TOPIC                VARCHAR2(400), 
TMP_INDICATOR_NAME                 VARCHAR2(400), 
TMP_INDICATOR_SHORT_DEFINITION         VARCHAR2(1000), 
TMP_INDICATOR_LONG_DEFINITION          VARCHAR2(4000), 
TMP_INDICATOR_MEASURE_UNIT             VARCHAR2(20), 
TMP_INDICATOR_PERIODICITY              VARCHAR2(40), 
TMP_INDICATOR_BASE_PERIOD              VARCHAR2(50), 
TMP_INDICATOR_OTHER_NOTES            VARCHAR2(2000), 
TMP_INDICATOR_AGGREGATION_METHOD       VARCHAR2(50), 
TMP_INDICATOR_LIMITATION_EXCEPTION    VARCHAR2(4000), 
TMP_INDICATOR_NOTES_ORIGIN_SOURCE      VARCHAR2(4000), 


CONSTRAINT PK_TMP_INDICATOR PRIMARY KEY (TMP_INDICATOR_ID)
using index TABLESPACE DIM_INDEX
) 
TABLESPACE DIM_DATA;


CREATE SEQUENCE SEQ_TMP_INDICATOR
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

COMMENT ON TABLE  TMP_INDICATOR                                IS  'TEMPORARY TABLE OF SERIES';
COMMENT ON COLUMN TMP_INDICATOR.TMP_INDICATOR_ID               IS  'TECHNICAL UNIQUE IDENTIFIER OF SERIES';
COMMENT ON COLUMN TMP_INDICATOR.TMP_INDICATOR_CODE             IS  'FUNCTIONAL UNIQUE IDENTIFIER OF SERIES';
COMMENT ON COLUMN TMP_INDICATOR.TMP_INDICATOR_NAME             IS  'NAME OF SERIES';
COMMENT ON COLUMN TMP_INDICATOR.TMP_INDICATOR_TOPIC            IS  'TOPIC OF  SERIES';
COMMENT ON COLUMN TMP_INDICATOR.TMP_INDICATOR_SHORT_DEFINITION     IS  'SHORT DEFINITION OF SERIES';
COMMENT ON COLUMN TMP_INDICATOR.TMP_INDICATOR_LONG_DEFINITION      IS  'LONG DEFINITION OF SERIES';
COMMENT ON COLUMN TMP_INDICATOR.TMP_INDICATOR_MEASURE_UNIT         IS  'MEASURE UNIT';
COMMENT ON COLUMN TMP_INDICATOR.TMP_INDICATOR_PERIODICITY          IS  'PERIODICITY';
COMMENT ON COLUMN TMP_INDICATOR.TMP_INDICATOR_AGGREGATION_METHOD   IS  'AGGREGATION METHOD';
COMMENT ON COLUMN TMP_INDICATOR.TMP_INDICATOR_LIMITATION_EXCEPTION  IS  'LIMITATIONS AND EXCEPTION';
COMMENT ON COLUMN TMP_INDICATOR.TMP_INDICATOR_NOTES_ORIGIN_SOURCE   IS  'NOTES ORIGIN SOURCE';



CREATE OR REPLACE TRIGGER TMP_INDICATOR_ON_INSERT
BEFORE INSERT ON TMP_INDICATOR
FOR EACH ROW

BEGIN
SELECT SEQ_TMP_INDICATOR.NEXTVAL
INTO :NEW.TMP_INDICATOR_ID
FROM DUAL;
END;
/
