CREATE TABLE TMP_COUNTRY (

TMP_COUNTRY_ID                NUMBER(15,0)  NOT NULL,
TMP_COUNTRY_CODE              VARCHAR2(20)  NOT NULL, 
TMP_COUNTRY_SHORT_NAME        VARCHAR2(100) NOT NULL, 
TMP_COUNTRY_LONG_NAME         VARCHAR2(500) NOT NULL, 
TMP_COUNTRY_CURRENCY_UNIT     VARCHAR2(200), 
TMP_COUNTRY_SPECIAL_NOTES     VARCHAR2(2000), 
TMP_COUNTRY_REGION            VARCHAR2(100),

CONSTRAINT PK_TMP_COUNTRY PRIMARY KEY (TMP_COUNTRY_ID)
using index TABLESPACE DIM_INDEX
) 
TABLESPACE DIM_DATA;


CREATE SEQUENCE SEQ_TMP_COUNTRY
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

COMMENT ON TABLE  TMP_COUNTRY                              IS  'TEMPORARY TABLE OF COUNTRY';
COMMENT ON COLUMN TMP_COUNTRY.TMP_COUNTRY_ID               IS  'TECHNICAL UNIQUE IDENTIFIER OF COUNTRY';
COMMENT ON COLUMN TMP_COUNTRY.TMP_COUNTRY_CODE             IS  'FUNCTIONAL UNIQUE IDENTIFIER OF COUNTRY';
COMMENT ON COLUMN TMP_COUNTRY.TMP_COUNTRY_SHORT_NAME       IS  'SHORT NAME OF COUNTRY';
COMMENT ON COLUMN TMP_COUNTRY.TMP_COUNTRY_LONG_NAME        IS  'LONG NAME OF  COUNTRY';
COMMENT ON COLUMN TMP_COUNTRY.TMP_COUNTRY_CURRENCY_UNIT    IS  'COUNTRY_CURRENCY_UNIT';
COMMENT ON COLUMN TMP_COUNTRY.TMP_COUNTRY_SPECIAL_NOTES    IS  'SPECIAL NOTES';
COMMENT ON COLUMN TMP_COUNTRY.TMP_COUNTRY_REGION           IS  'COUNTRY REGION';



CREATE OR REPLACE TRIGGER TMP_COUNTRY_ON_INSERT
BEFORE INSERT ON TMP_COUNTRY
FOR EACH ROW

BEGIN
SELECT SEQ_TMP_COUNTRY.NEXTVAL
INTO :NEW.TMP_COUNTRY_ID
FROM DUAL;
END;
/
